# Generated by Django 5.2.6 on 2025-10-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(db_column='ID_Teacher', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='FIO', max_length=35)),
                ('post', models.CharField(db_column='Post', max_length=20)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=15, null=True)),
                ('education', models.CharField(db_column='Education', max_length=70)),
                ('lesson', models.CharField(db_column='Lesson', max_length=15)),
                ('up_category', models.CharField(blank=True, db_column='Up_category', max_length=30, null=True)),
                ('prof_retrain', models.CharField(blank=True, db_column='Prof_retrain', max_length=70, null=True)),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'db_table': 'Teacher',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
