# Generated by Django 5.2.6 on 2025-10-30 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(db_column='ID_Subject', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='Full_name', max_length=35)),
                ('short_name', models.CharField(blank=True, db_column='Short_name', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.CharField(blank=True, db_column='Education', max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(db_column='ID_Cabinet', primary_key=True, serialize=False)),
                ('number', models.CharField(db_column='Number_Cabinet', max_length=20)),
                ('teacher', models.ForeignKey(db_column='ID_Teacher', on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'db_table': 'Cabinet',
            },
        ),
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.AutoField(db_column='ID_Class', primary_key=True, serialize=False)),
                ('number', models.CharField(db_column='Number_Class', max_length=20)),
                ('cabinet', models.ForeignKey(db_column='ID_Cabinet', on_delete=django.db.models.deletion.CASCADE, to='main.cabinet')),
                ('teacher', models.ForeignKey(db_column='ID_Teacher', on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='ID_Student', primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, db_column='FIO_Student', max_length=35, null=True)),
                ('parent_name', models.CharField(blank=True, db_column='FIO_Parent', max_length=35, null=True)),
                ('birth_date', models.DateField(blank=True, db_column='Date', max_length=15, null=True)),
                ('skills', models.CharField(blank=True, db_column='Skills', max_length=20, null=True)),
                ('address', models.CharField(db_column='Adress', max_length=50)),
                ('phone', models.CharField(db_column='Phone', max_length=11)),
                ('school_class', models.ForeignKey(db_column='ID_Class', on_delete=django.db.models.deletion.CASCADE, to='main.schoolgroup')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(db_column='ID_Schedule', primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, db_column='Inf', max_length=100, null=True)),
                ('cabinet', models.ForeignKey(db_column='ID_Cabinet', on_delete=django.db.models.deletion.CASCADE, to='main.cabinet')),
                ('school_class', models.ForeignKey(db_column='ID_Class', on_delete=django.db.models.deletion.CASCADE, to='main.schoolgroup')),
                ('subject', models.ForeignKey(db_column='ID_Subject', on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
    ]
