# Generated by Django 5.2.8 on 2025-11-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cabinet_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='up_category',
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, db_column='Experience', max_length=30, null=True),
        ),
    ]
