# Generated by Django 5.2.8 on 2025-11-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_teacher_up_category_teacher_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='skills',
            new_name='snills',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lesson',
            field=models.CharField(db_column='Lesson', max_length=60),
        ),
    ]
