# Generated by Django 5.2.8 on 2025-11-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_skills_student_snills_alter_teacher_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(db_column='Address', max_length=50),
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.IntegerField(default=0, verbose_name='Часов в неделю')),
                ('is_main_subject', models.BooleanField(default=False, verbose_name='Основной предмет')),
                ('subject', models.ForeignKey(db_column='ID_Subject', on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('teacher', models.ForeignKey(db_column='ID_Teacher', on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name': 'Предмет учителя',
                'verbose_name_plural': 'Предметы учителей',
                'db_table': 'Teacher_Subject',
                'unique_together': {('teacher', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(through='main.TeacherSubject', to='main.subject', verbose_name='Преподаваемые предметы'),
        ),
    ]
