# Generated by Django 5.2.8 on 2025-11-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_address_teachersubject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
