# Generated by Django 5.2.8 on 2025-11-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_teacher_subjects_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
    ]
