# Generated by Django 5.2.8 on 2025-11-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_teacher_options_alter_teacher_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, db_column='Inf', max_length=100, null=True)),
                ('subject', models.ForeignKey(db_column='ID_Subject', on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('teacher', models.ForeignKey(db_column='ID_Teacher', on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name': 'Учитель-Предмет',
                'verbose_name_plural': 'Учителя-Предметы',
                'db_table': 'Teacher_Subject',
            },
        ),
    ]
