# Generated by Django 5.2.8 on 2025-11-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_teachersubject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day_of_week', 'lesson_number'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'verbose_name': 'Связь Учитель-Предмет', 'verbose_name_plural': 'Связи Учитель-Предмет'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lesson',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='main.subject', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(db_column='Adress', default='Не указан', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, db_column='Date', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='snills',
            field=models.CharField(blank=True, db_column='Snills', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(db_column='Subject', on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together={('subject', 'teacher')},
        ),
    ]
