# Generated by Django 5.2.8 on 2025-11-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_schedule_options_alter_teachersubject_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 урок (8:30-9:10)'), (2, '2 урок (9:20-10:00)'), (3, '3 урок (10:10-10:50)'), (4, '4 урок (11:10-11:50)'), (5, '5 урок (12:10-12:50)'), (6, '6 урок (13:00-13:40)'), (7, '7 урок (13:50-14:30)'), (8, '8 урок (14:40-15:20)'), (9, '9 урок (15:30-16:10)')], default=1, verbose_name='Номер урока'),
        ),
        migrations.CreateModel(
            name='ExtraActivity',
            fields=[
                ('id', models.AutoField(db_column='ID_ExtraActivity', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100, verbose_name='Название занятия')),
                ('description', models.TextField(blank=True, db_column='Description', null=True, verbose_name='Описание')),
                ('activity_type', models.CharField(choices=[('sport', 'Спортивное'), ('art', 'Творческое'), ('science', 'Научное'), ('language', 'Языковое'), ('other', 'Другое')], db_column='Activity_Type', default='other', max_length=20, verbose_name='Тип занятия')),
                ('max_students', models.PositiveSmallIntegerField(db_column='Max_Students', default=15, verbose_name='Максимум учеников')),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True, verbose_name='Активно')),
                ('teacher', models.ForeignKey(db_column='ID_Teacher', on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Дополнительное занятие',
                'verbose_name_plural': 'Дополнительные занятия',
                'db_table': 'ExtraActivity',
            },
        ),
        migrations.CreateModel(
            name='ExtraSchedule',
            fields=[
                ('id', models.AutoField(db_column='ID_ExtraSchedule', primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default=1, verbose_name='День недели')),
                ('lesson_number', models.PositiveSmallIntegerField(choices=[(1, '1 урок (8:00-8:45)'), (2, '2 урок (8:55-9:40)'), (3, '3 урок (9:50-10:35)'), (4, '4 урок (10:45-11:30)'), (5, '5 урок (11:40-12:25)'), (6, '6 урок (12:35-13:20)'), (7, '7 урок (13:30-14:15)'), (8, '8 урок (14:25-15:10)'), (9, '9 урок (15:20-16:05)'), (10, 'После уроков (16:15-17:00)'), (11, 'После уроков (17:10-17:55)')], default=10, verbose_name='Время занятия')),
                ('activity', models.ForeignKey(db_column='ID_ExtraActivity', on_delete=django.db.models.deletion.CASCADE, to='main.extraactivity', verbose_name='Занятие')),
                ('cabinet', models.ForeignKey(db_column='ID_Cabinet', on_delete=django.db.models.deletion.CASCADE, to='main.cabinet', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Расписание доп. занятий',
                'verbose_name_plural': 'Расписание доп. занятий',
                'db_table': 'ExtraSchedule',
                'ordering': ['day_of_week', 'lesson_number'],
            },
        ),
    ]
